version: "3"
services:
  db:
    image: "apacheignite/ignite:2.8.0"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
        reservations:
          cpus: '2.0'
          memory: 1G
  benchmark:
    build: ./
