version: "3"
services:
  db:
    image: "redis:6-alpine"
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 4G
        reservations:
          cpus: '2.0'
          memory: 4G
  benchmark:
    build: ./
